version: '3.7'

volumes:
  mongodb:
  web:

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: main-ingredient
    ports:
      - 3001:27017
    volumes:
      - ./docker/database:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongodb:/data/configdb
  web:
    image: main-ingredient:latest
    environment:
        mongoDBUri: mongodb://mongodb:27017/recipes
        port: 3000
    ports:
      - 3000:3000
    volumes:
      - web:/opt
    depends_on:
      - mongodb
